"""Turns computed figures into plain business English.

Every panel in the dashboard carries three lines: what the number is, what
it means commercially, and what to do about it. Those lines are generated
here from the actual computed values rather than written by hand, so they
stay correct when the data is refreshed.

This is deliberately deterministic rather than generated by a language
model. The numbers quoted in a board pack have to reconcile exactly with
the numbers in the table beside them, the wording has to be identical each
time the same data is loaded, and it has to work with no external service
and no per-query cost. A template that interpolates verified figures meets
all three; a language model meets none of them reliably.
"""
from __future__ import annotations

from app.config import BASE_CURRENCY, BASE_CURRENCY_SYMBOL


def fmt_money(value: float | None) -> str:
    if value is None:
        return "n/a"
    sign = "-" if value < 0 else ""
    v = abs(float(value))
    if v >= 1_000_000:
        return f"{sign}{BASE_CURRENCY_SYMBOL}{v / 1_000_000:.1f}M"
    if v >= 1_000:
        return f"{sign}{BASE_CURRENCY_SYMBOL}{v / 1_000:.0f}k"
    return f"{sign}{BASE_CURRENCY_SYMBOL}{v:.0f}"


def _plural(n: float, singular: str, plural: str | None = None) -> str:
    return singular if n == 1 else (plural or f"{singular}s")


def _story(headline: str, meaning: str, action: str) -> dict:
    return {"headline": headline, "what_it_means": meaning, "recommended_action": action}


def customer_value_story(result: dict) -> dict:
    c = result["concentration"]
    top_name = c.get("top_customer_name") or "the largest account"
    return _story(
        headline=(
            f"{c['top_5_share_pct']}% of all value added comes from just five accounts, "
            f"and {c['top_customer_share_pct']}% from {top_name} alone."
        ),
        meaning=(
            "The order book is highly concentrated. That is efficient — a small number of "
            "relationships carry most of the value, and they are cheaper to serve than many small "
            "ones — but it is also the biggest single commercial risk the business carries. "
            f"Losing {top_name} would remove roughly {c['top_customer_share_pct']}% of value added "
            "at a stroke, and there is no quick replacement for an account of that size."
        ),
        action=(
            f"Put a named, board-visible relationship plan behind the top five accounts, and treat "
            f"{top_name} as a standing agenda item. In parallel, set a growth target for the "
            "mid-tier accounts specifically to reduce dependence on the top of the book."
        ),
    )


def pricing_story(result: dict) -> dict:
    s = result["summary"]
    worst = s.get("worst_below_cost_customer") or "one account"
    top_disc = s.get("top_discount_customer") or "one account"
    return _story(
        headline=(
            f"The automated estimate is overridden on {s['overridden_pct']}% of jobs — "
            f"{fmt_money(s['discount_total'])} given away in price reductions against "
            f"{fmt_money(s['uplift_total'])} added back in uplifts."
        ),
        meaning=(
            "Almost no job leaves the estimating system at the price the system calculated. The "
            "reductions and uplifts very nearly cancel out, so this is not money quietly leaking — "
            "but it does mean the automated price is effectively advisory, and the real pricing "
            "decision is being made by individual judgement on every single quote. That makes "
            "pricing dependent on who happens to handle the job, hard to review, and impossible to "
            f"improve systematically. It also concentrates: {top_disc} alone absorbed "
            f"{fmt_money(s['top_discount_amount'])} of the reductions, and "
            f"{s['below_cost_jobs']} {_plural(s['below_cost_jobs'], 'job')} were delivered at "
            f"negative value added, {s['worst_below_cost_share_pct']}% of it on {worst}."
        ),
        action=(
            "Two things. First, review the negative-margin jobs directly — some will be genuine "
            "loss-makers and some will be credit notes or mis-bookings, and the distinction "
            "matters. Second, treat the override rate as a signal about the estimating system "
            "itself: if the calculated price is right, it should not need changing on 49 jobs in "
            "every 50. Recalibrating it would remove a manual step from every quote and make "
            "pricing defensible."
        ),
    )


def reorder_story(result: dict) -> dict:
    s = result["summary"]
    return _story(
        headline=(
            f"{s['overdue_count']} customers are past the point where they would normally have "
            f"reordered, and {s['due_soon_count']} more are due within a fortnight — around "
            f"{fmt_money(s['expected_value_next_30_days'])} of expected work in the next 30 days."
        ),
        meaning=(
            "Most customers reorder on a rhythm, even when nobody has written that rhythm down. "
            "Knowing each account's normal gap turns the order book from something that arrives "
            "into something that can be anticipated: the sales team can see who is due before the "
            "customer calls, and production has an early read on what is coming."
        ),
        action=(
            "Work the overdue list first — those are customers whose own pattern says they should "
            "have been in touch by now, which is the cheapest possible sales lead. Then use the "
            "due-soon list to give production a forward view of likely load."
        ),
    )


def churn_story(result: dict) -> dict:
    counts = result["status_counts"]
    at_risk = counts.get("At Risk", 0)
    dormant = counts.get("Dormant", 0)
    return _story(
        headline=(
            f"{at_risk} {_plural(at_risk, 'account has', 'accounts have')} gone quieter than their "
            f"own pattern would predict, and {dormant} "
            f"{_plural(dormant, 'has', 'have')} effectively stopped — "
            f"{fmt_money(result['dormant_lifetime_value_at_stake'])} of lifetime value."
        ),
        meaning=(
            "Customers rarely announce that they are leaving; they simply stop calling. Judging "
            "silence against each account's own habit catches that early — six weeks of quiet from "
            "a fortnightly customer is a genuine warning, while the same six weeks from a "
            "twice-a-year customer means nothing. Reacting while an account is merely quiet is "
            "materially cheaper than winning it back once it has gone."
        ),
        action=(
            "Give the at-risk list to the relevant account managers this week with a simple "
            "instruction: make contact and find out whether anything has changed. Treat the "
            "dormant list as a win-back campaign with a budget, not as routine follow-up."
        ),
    )


def seasonality_story(result: dict) -> dict:
    s = result["summary"]
    ratio = s.get("peak_to_trough_ratio")
    ratio_text = f"{ratio:.1f} times" if ratio else "several times"
    return _story(
        headline=(
            f"{s['peak_month']} runs at {s['peak_index']}% of an average month while "
            f"{s['trough_month']} runs at {s['trough_index']}% — a peak roughly {ratio_text} the "
            "size of the quietest month."
        ),
        meaning=(
            "Demand is strongly seasonal, and because the constraint in this business is press "
            "time rather than order count, that swing lands directly on capacity. The peak months "
            "risk overtime, outsourcing and missed dates; the quiet months carry the same fixed "
            "cost against much less work. Both are expensive, and both are predictable."
        ),
        action=(
            f"Plan shift patterns, holidays and maintenance against the seasonal shape rather than "
            f"against last month's actuals — the next-month projection is "
            f"{fmt_money(s['forecast_next_month_sales'])} of sales and "
            f"{s['forecast_next_month_press']} press hours. Use the quiet months deliberately: "
            "they are the natural window for maintenance, training and targeted campaigns aimed at "
            "work that does not compete with the peak."
        ),
    )


def delivery_story(result: dict) -> dict:
    s = result["summary"]
    direction = s.get("direction", "stable")
    if direction == "slower":
        trend = f"Turnaround has slipped by about {abs(s['recent_vs_prior_days'])} days recently"
    elif direction == "faster":
        trend = f"Turnaround has improved by about {abs(s['recent_vs_prior_days'])} days recently"
    else:
        trend = "Turnaround has been broadly stable"
    return _story(
        headline=(
            f"Half of all work ships within {s['median_days']} days of being booked, but the "
            f"slowest tenth takes {s['p90_days']} days or more. {trend}."
        ),
        meaning=(
            f"Speed is one of the few things a customer notices without being told, and the spread "
            f"matters more than the average: {s['fastest_work_type']} work turns around in about "
            f"{s['fastest_median_days']} days while {s['slowest_work_type']} takes roughly "
            f"{s['slowest_median_days']}. A long tail of very slow jobs is where complaints, "
            "expedite costs and lost repeat business come from, and those jobs are identifiable "
            "well before they become problems."
        ),
        action=(
            "Set a published turnaround promise per product rather than one company-wide figure, "
            "since the products genuinely differ. Then review the jobs running far beyond their own "
            "product's norm — those are where the recoverable time sits."
        ),
    )


def repeat_business_story(result: dict) -> dict:
    s = result["summary"]
    return _story(
        headline=(
            f"{s['repeat_revenue_pct']}% of revenue comes from titles printed before — "
            f"{s['repeat_titles']} recurring {_plural(s['repeat_titles'], 'title')}, of which "
            f"{s['titles_due_reprint']} are now overdue against their own reprint cycle "
            f"(about {fmt_money(s['reprint_pipeline_value'])} of work)."
        ),
        meaning=(
            "Reprint work is the most profitable revenue in a print business: the origination is "
            "already done, the specification is proven, and the job runs with far less setup risk. "
            "It is also the most predictable, because titles reprint on a cycle. Treating it as "
            "orders that happen to arrive, rather than as a pipeline that can be called, leaves "
            "the easiest revenue in the business to chance — and to competitors, who only need to "
            "quote against a specification the customer already has."
        ),
        action=(
            "Turn the overdue reprint list into a standing call list for the sales team. A title "
            "that is past its normal reprint cycle is either about to be ordered, about to be "
            "ordered elsewhere, or discontinued — and all three are worth knowing early."
        ),
    )


def quote_guard_story(result: dict) -> dict:
    if not result.get("available"):
        return _story(
            headline="Not enough priced history to benchmark quotes.",
            meaning="The pricing benchmark needs a reasonable volume of completed, priced jobs before it can tell a keen price from a normal one.",
            action="Revisit once more history is loaded.",
        )
    m = result["metrics"]
    return _story(
        headline=(
            f"A model trained on past jobs predicts the achieved price to within "
            f"{m['median_abs_pct_error']}% for a typical job, and flags {result['flagged_count']} "
            f"held-out {_plural(result['flagged_count'], 'job')} sold more than "
            f"{result['threshold_pct']:.0f}% below the going rate."
        ),
        meaning=(
            "Specification and input costs explain most of what a job sells for, which means it is "
            "possible to say what comparable work has historically commanded. That gives the "
            "estimator a second opinion at the moment of quoting — not a price to obey, but a "
            "reference point, and a prompt when a quote is drifting well below what similar work "
            "has achieved. Applied at the point of sale it protects margin before it is committed, "
            "rather than reporting on it afterwards."
        ),
        action=(
            "Surface the benchmark inside the estimating workflow so it appears while the quote is "
            "being built. Start it advisory — showing the comparison without blocking anything — "
            "and review the flagged jobs monthly to check the model is calling them fairly before "
            "giving it any authority."
        ),
    )


def churn_model_story(result: dict) -> dict:
    if not result.get("available"):
        return _story(
            headline="Not enough order history to model churn risk.",
            meaning="The risk model needs several years of ordering behaviour across a reasonable number of accounts before its predictions are trustworthy.",
            action="Revisit once more history is loaded.",
        )
    m = result["metrics"]
    bands = result["band_counts"]
    verdict = (
        "meaningfully better than simply asking who is overdue"
        if m["beats_baseline"] else
        "no better than simply asking who is overdue, so the simpler rule should be preferred"
    )
    return _story(
        headline=(
            f"{bands.get('High', 0)} accounts are scored high-risk of not ordering in the next "
            f"{m['lookahead_days']} days. Tested on later months than it was trained on, the model "
            f"scores {m['auc']} against a benchmark of {m['baseline_auc']} — {verdict}."
        ),
        meaning=(
            "The rules-based view asks whether a customer has gone quiet. This asks the forward "
            "question — how likely are they to come back — and weighs several signals at once: how "
            "overdue they are relative to their own habit, whether their spend is trending down, "
            "how established the relationship is. Because it was tested only on months after the "
            "ones it learned from, the score reflects how it would have performed in practice "
            "rather than how well it can describe the past."
        ),
        action=(
            "Use the risk score to prioritise the account managers' call list each month, ahead of "
            "the simple overdue list. Treat it as ranking rather than verdict — with 50 accounts "
            "the model is working from limited evidence, and it should be re-tested as more "
            "history accumulates."
        ),
    )


def data_quality_story(summary: dict) -> dict:
    split = summary.get("currency_split", [])
    parts = ", ".join(f"{c['currency']} {c['job_count']} jobs" for c in split) or "multiple currencies"
    return _story(
        headline=(
            f"The order book is billed in more than one currency ({parts}), and prices are recorded "
            "in the customer's own currency in a single column."
        ),
        meaning=(
            "Added together untouched, those figures produce a total that is neither pounds nor "
            f"euros and overstates the book by roughly "
            f"{fmt_money(summary.get('naive_mixed_total', 0) - summary.get('total_sell_price', 0))}. "
            f"Every figure in this dashboard is therefore converted to {BASE_CURRENCY} first, at a "
            f"stated planning rate, so the totals are comparable across regions."
        ),
        action=(
            "Agree a single reporting currency and a rate-setting convention for management "
            "reporting, and hold the rate constant within a reporting period so movements reflect "
            "trading rather than exchange rates."
        ),
    )


def executive_summary(stories: dict[str, dict]) -> list[dict]:
    """The handful of findings worth a senior manager's attention first."""
    order = ["pricing", "customer_value", "repeat_business", "churn", "seasonality"]
    out = []
    for key in order:
        story = stories.get(key)
        if story:
            out.append({"area": key, "headline": story["headline"]})
    return out
