# Generated by Django 5.2.16 on 2026-07-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('rows_read', models.IntegerField()),
                ('rows_inserted', models.IntegerField()),
                ('rows_updated', models.IntegerField()),
                ('quality_counts', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('job_status', models.CharField(blank=True, max_length=64, null=True)),
                ('sales_in', models.DateField(db_index=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.CharField(blank=True, max_length=32, null=True)),
                ('week_no', models.IntegerField(null=True)),
                ('sales_out', models.DateField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('mup_pct', models.FloatField(null=True)),
                ('va_amount', models.FloatField(null=True)),
                ('va_per_24', models.FloatField(null=True)),
                ('va_pct', models.FloatField(null=True)),
                ('va_per_k', models.FloatField(null=True)),
                ('rebate', models.FloatField(null=True)),
                ('purchases', models.FloatField(null=True)),
                ('press_hrs', models.FloatField(null=True)),
                ('impressions', models.FloatField(null=True)),
                ('handling', models.FloatField(null=True)),
                ('labour', models.FloatField(null=True)),
                ('paper', models.FloatField(null=True)),
                ('labmup', models.FloatField(null=True)),
                ('manadj', models.FloatField(null=True)),
                ('mupnett', models.FloatField(null=True)),
                ('plates', models.FloatField(null=True)),
                ('amt_inv', models.FloatField(null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rep', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('industry', models.CharField(blank=True, max_length=128, null=True)),
                ('work_type', models.CharField(blank=True, max_length=64, null=True)),
                ('product_type', models.CharField(blank=True, max_length=128, null=True)),
                ('binding_type', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('ship_date', models.DateField(null=True)),
                ('sell_price_gbp', models.FloatField(null=True)),
                ('va_amount_gbp', models.FloatField(null=True)),
                ('purchases_gbp', models.FloatField(null=True)),
                ('labour_gbp', models.FloatField(null=True)),
                ('paper_gbp', models.FloatField(null=True)),
                ('product_type_norm', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('binding_type_filled', models.CharField(blank=True, max_length=128, null=True)),
                ('is_credit', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('has_date_anomaly', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_job',
            },
        ),
    ]
