# Generated by Django 5.2.16 on 2026-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='product_group',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
